// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'danmaku_item.freezed.dart';
part 'danmaku_item.g.dart';

@freezed
sealed class DanmakuItem with _$DanmakuItem {
  const factory DanmakuItem({
    required int id,
    required int userId,
    required String content,
    required String color,
    required String vTime,
  }) = _DanmakuItem;

  factory DanmakuItem.fromJson(Map<String, dynamic> json) =>
      _$DanmakuItemFromJson(json);
}
