// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'episode.freezed.dart';
part 'episode.g.dart';

@freezed
sealed class Episode with _$Episode {
  const factory Episode({required String label, required String url}) =
      _Episode;

  factory Episode.fromJson(Map<String, dynamic> json) =>
      _$EpisodeFromJson(json);
}

@freezed
sealed class PlaySource with _$PlaySource {
  const factory PlaySource({
    required String name,
    required String parseApi,
    required List<Episode> episodes,
    required bool needResolve,
    required Map<String, String> headers,
  }) = _PlaySource;

  factory PlaySource.fromJson(Map<String, dynamic> json) =>
      _$PlaySourceFromJson(json);
}
