// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'recommend_video.freezed.dart';
part 'recommend_video.g.dart';

@freezed
sealed class BannerItem with _$BannerItem {
  const factory BannerItem({
    required int id,
    required String name,
    required String content,
    required int reqType,
    required String reqContent,
    required String realPackageId,
  }) = _BannerItem;

  factory BannerItem.fromJson(Map<String, dynamic> json) =>
      _$BannerItemFromJson(json);
}

@freezed
sealed class HomeRecommendData with _$HomeRecommendData {
  const factory HomeRecommendData({
    required List<BannerItem> banners,
    required List<HomeVideoSection> videos,
  }) = _HomeRecommendData;

  factory HomeRecommendData.fromJson(Map<String, dynamic> json) =>
      _$HomeRecommendDataFromJson(json);
}

@freezed
sealed class HomeVideoSection with _$HomeVideoSection {
  const factory HomeVideoSection({
    required int id,
    required String name,
    required int typeId,
    required bool hasMore,
    required int moreReqType,
    required String moreText,
    required List<RecommendVodItem> vlist,
  }) = _HomeVideoSection;

  factory HomeVideoSection.fromJson(Map<String, dynamic> json) =>
      _$HomeVideoSectionFromJson(json);
}

@freezed
sealed class RecommendVodItem with _$RecommendVodItem {
  const factory RecommendVodItem({
    required int vodId,
    required String vodName,
    required String vodPic,
    required String vodRemarks,
    required int typeId,
  }) = _RecommendVodItem;

  factory RecommendVodItem.fromJson(Map<String, dynamic> json) =>
      _$RecommendVodItemFromJson(json);
}
