// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'video_list.freezed.dart';
part 'video_list.g.dart';

@freezed
sealed class VideoListRequest with _$VideoListRequest {
  const factory VideoListRequest({
    required BigInt pg,
    required BigInt tid,
    required String class_,
    required String area,
    required String lang,
    required String year,
    required String order,
    required String token,
  }) = _VideoListRequest;

  factory VideoListRequest.fromJson(Map<String, dynamic> json) =>
      _$VideoListRequestFromJson(json);
}

@freezed
sealed class VodListItem with _$VodListItem {
  const factory VodListItem({
    required int typeId,
    required PlatformInt64 vodId,
    required String vodName,
    required String vodPic,
    required String vodRemarks,
  }) = _VodListItem;

  factory VodListItem.fromJson(Map<String, dynamic> json) =>
      _$VodListItemFromJson(json);
}
