// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'episode.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'video_detail.freezed.dart';
part 'video_detail.g.dart';

@freezed
sealed class BackendVideoDetail with _$BackendVideoDetail {
  const factory BackendVideoDetail({
    required int commentCount,
    required int isCollect,
    required VodInfo vodInfo,
  }) = _BackendVideoDetail;

  factory BackendVideoDetail.fromJson(Map<String, dynamic> json) =>
      _$BackendVideoDetailFromJson(json);
}

@freezed
sealed class FrontendVideoDetail with _$FrontendVideoDetail {
  const factory FrontendVideoDetail({
    required List<PlaySource> playSources,
    required BackendVideoDetail videoInfo,
  }) = _FrontendVideoDetail;

  factory FrontendVideoDetail.fromJson(Map<String, dynamic> json) =>
      _$FrontendVideoDetailFromJson(json);
}

@freezed
sealed class VodInfo with _$VodInfo {
  const factory VodInfo({
    required int groupId,
    required int typeId,
    required int typeId1,
    required PlatformInt64 vodId,
    required String vodName,
    required String vodEn,
    required String vodSub,
    required String vodActor,
    required String vodDirector,
    required String vodWriter,
    required String vodArea,
    required String vodLang,
    required String vodYear,
    required String vodClass,
    required String vodPic,
    required String vodPicThumb,
    required String vodPicSlide,
    String? vodPicScreenshot,
    required String vodBlurb,
    required String vodContent,
    required String vodRemarks,
    required String vodPubdate,
    required int vodTotal,
    required String vodSerial,
    required String vodDuration,
    required String vodScore,
    required int vodScoreAll,
    required int vodScoreNum,
    required PlatformInt64 vodDoubanId,
    required String vodDoubanScore,
    required PlatformInt64 vodHits,
    required PlatformInt64 vodHitsDay,
    required PlatformInt64 vodHitsWeek,
    required PlatformInt64 vodHitsMonth,
    required PlatformInt64 vodUp,
    required PlatformInt64 vodDown,
    required int vodStatus,
    required int vodIsend,
    required int vodLock,
    required int vodLevel,
    required int vodCopyright,
    required int vodPoints,
    required int vodPointsPlay,
    required int vodPointsDown,
    required int vodTrysee,
    required int vodPlot,
    required String vodPlotName,
    required String vodPlotDetail,
    required String vodPlayFrom,
    required String vodPlayServer,
    required String vodPlayNote,
    required String vodPlayUrl,
    required String vodDownFrom,
    required String vodDownServer,
    required String vodDownNote,
    required String vodDownUrl,
    required String vodJumpurl,
    required String vodPwd,
    required String vodPwdUrl,
    required String vodPwdPlay,
    required String vodPwdPlayUrl,
    required String vodPwdDown,
    required String vodPwdDownUrl,
    required String vodRelVod,
    required String vodRelArt,
    required String vodTag,
    required String vodLetter,
    required String vodColor,
    required String vodAuthor,
    required String vodBehind,
    required String vodState,
    required String vodVersion,
    required String vodWeekday,
    required String vodTv,
    required String vodTpl,
    required String vodTplPlay,
    required String vodTplDown,
    required String vodReurl,
    required PlatformInt64 vodTime,
    required PlatformInt64 vodTimeAdd,
    required PlatformInt64 vodTimeHits,
    required PlatformInt64 vodTimeMake,
    List<VodPlayer>? vodUrlWithPlayer,
  }) = _VodInfo;

  factory VodInfo.fromJson(Map<String, dynamic> json) =>
      _$VodInfoFromJson(json);
}

@freezed
sealed class VodPlayer with _$VodPlayer {
  const factory VodPlayer({
    required String code,
    required String name,
    required String url,
    required String headers,
    required String parseApi,
    required String extraParseApi,
    required bool parseSecret,
    required String linkFeatures,
    required String unLinkFeatures,
    required List<String> coreParams,
  }) = _VodPlayer;

  factory VodPlayer.fromJson(Map<String, dynamic> json) =>
      _$VodPlayerFromJson(json);
}
