// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'video_detail.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_BackendVideoDetail _$BackendVideoDetailFromJson(Map<String, dynamic> json) =>
    _BackendVideoDetail(
      commentCount: (json['commentCount'] as num).toInt(),
      isCollect: (json['isCollect'] as num).toInt(),
      vodInfo: VodInfo.fromJson(json['vodInfo'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$BackendVideoDetailToJson(_BackendVideoDetail instance) =>
    <String, dynamic>{
      'commentCount': instance.commentCount,
      'isCollect': instance.isCollect,
      'vodInfo': instance.vodInfo,
    };

_FrontendVideoDetail _$FrontendVideoDetailFromJson(Map<String, dynamic> json) =>
    _FrontendVideoDetail(
      playSources: (json['playSources'] as List<dynamic>)
          .map((e) => PlaySource.fromJson(e as Map<String, dynamic>))
          .toList(),
      videoInfo: BackendVideoDetail.fromJson(
        json['videoInfo'] as Map<String, dynamic>,
      ),
    );

Map<String, dynamic> _$FrontendVideoDetailToJson(
  _FrontendVideoDetail instance,
) => <String, dynamic>{
  'playSources': instance.playSources,
  'videoInfo': instance.videoInfo,
};

_VodInfo _$VodInfoFromJson(Map<String, dynamic> json) => _VodInfo(
  groupId: (json['groupId'] as num).toInt(),
  typeId: (json['typeId'] as num).toInt(),
  typeId1: (json['typeId1'] as num).toInt(),
  vodId: (json['vodId'] as num).toInt(),
  vodName: json['vodName'] as String,
  vodEn: json['vodEn'] as String,
  vodSub: json['vodSub'] as String,
  vodActor: json['vodActor'] as String,
  vodDirector: json['vodDirector'] as String,
  vodWriter: json['vodWriter'] as String,
  vodArea: json['vodArea'] as String,
  vodLang: json['vodLang'] as String,
  vodYear: json['vodYear'] as String,
  vodClass: json['vodClass'] as String,
  vodPic: json['vodPic'] as String,
  vodPicThumb: json['vodPicThumb'] as String,
  vodPicSlide: json['vodPicSlide'] as String,
  vodPicScreenshot: json['vodPicScreenshot'] as String?,
  vodBlurb: json['vodBlurb'] as String,
  vodContent: json['vodContent'] as String,
  vodRemarks: json['vodRemarks'] as String,
  vodPubdate: json['vodPubdate'] as String,
  vodTotal: (json['vodTotal'] as num).toInt(),
  vodSerial: json['vodSerial'] as String,
  vodDuration: json['vodDuration'] as String,
  vodScore: json['vodScore'] as String,
  vodScoreAll: (json['vodScoreAll'] as num).toInt(),
  vodScoreNum: (json['vodScoreNum'] as num).toInt(),
  vodDoubanId: (json['vodDoubanId'] as num).toInt(),
  vodDoubanScore: json['vodDoubanScore'] as String,
  vodHits: (json['vodHits'] as num).toInt(),
  vodHitsDay: (json['vodHitsDay'] as num).toInt(),
  vodHitsWeek: (json['vodHitsWeek'] as num).toInt(),
  vodHitsMonth: (json['vodHitsMonth'] as num).toInt(),
  vodUp: (json['vodUp'] as num).toInt(),
  vodDown: (json['vodDown'] as num).toInt(),
  vodStatus: (json['vodStatus'] as num).toInt(),
  vodIsend: (json['vodIsend'] as num).toInt(),
  vodLock: (json['vodLock'] as num).toInt(),
  vodLevel: (json['vodLevel'] as num).toInt(),
  vodCopyright: (json['vodCopyright'] as num).toInt(),
  vodPoints: (json['vodPoints'] as num).toInt(),
  vodPointsPlay: (json['vodPointsPlay'] as num).toInt(),
  vodPointsDown: (json['vodPointsDown'] as num).toInt(),
  vodTrysee: (json['vodTrysee'] as num).toInt(),
  vodPlot: (json['vodPlot'] as num).toInt(),
  vodPlotName: json['vodPlotName'] as String,
  vodPlotDetail: json['vodPlotDetail'] as String,
  vodPlayFrom: json['vodPlayFrom'] as String,
  vodPlayServer: json['vodPlayServer'] as String,
  vodPlayNote: json['vodPlayNote'] as String,
  vodPlayUrl: json['vodPlayUrl'] as String,
  vodDownFrom: json['vodDownFrom'] as String,
  vodDownServer: json['vodDownServer'] as String,
  vodDownNote: json['vodDownNote'] as String,
  vodDownUrl: json['vodDownUrl'] as String,
  vodJumpurl: json['vodJumpurl'] as String,
  vodPwd: json['vodPwd'] as String,
  vodPwdUrl: json['vodPwdUrl'] as String,
  vodPwdPlay: json['vodPwdPlay'] as String,
  vodPwdPlayUrl: json['vodPwdPlayUrl'] as String,
  vodPwdDown: json['vodPwdDown'] as String,
  vodPwdDownUrl: json['vodPwdDownUrl'] as String,
  vodRelVod: json['vodRelVod'] as String,
  vodRelArt: json['vodRelArt'] as String,
  vodTag: json['vodTag'] as String,
  vodLetter: json['vodLetter'] as String,
  vodColor: json['vodColor'] as String,
  vodAuthor: json['vodAuthor'] as String,
  vodBehind: json['vodBehind'] as String,
  vodState: json['vodState'] as String,
  vodVersion: json['vodVersion'] as String,
  vodWeekday: json['vodWeekday'] as String,
  vodTv: json['vodTv'] as String,
  vodTpl: json['vodTpl'] as String,
  vodTplPlay: json['vodTplPlay'] as String,
  vodTplDown: json['vodTplDown'] as String,
  vodReurl: json['vodReurl'] as String,
  vodTime: (json['vodTime'] as num).toInt(),
  vodTimeAdd: (json['vodTimeAdd'] as num).toInt(),
  vodTimeHits: (json['vodTimeHits'] as num).toInt(),
  vodTimeMake: (json['vodTimeMake'] as num).toInt(),
  vodUrlWithPlayer: (json['vodUrlWithPlayer'] as List<dynamic>?)
      ?.map((e) => VodPlayer.fromJson(e as Map<String, dynamic>))
      .toList(),
);

Map<String, dynamic> _$VodInfoToJson(_VodInfo instance) => <String, dynamic>{
  'groupId': instance.groupId,
  'typeId': instance.typeId,
  'typeId1': instance.typeId1,
  'vodId': instance.vodId,
  'vodName': instance.vodName,
  'vodEn': instance.vodEn,
  'vodSub': instance.vodSub,
  'vodActor': instance.vodActor,
  'vodDirector': instance.vodDirector,
  'vodWriter': instance.vodWriter,
  'vodArea': instance.vodArea,
  'vodLang': instance.vodLang,
  'vodYear': instance.vodYear,
  'vodClass': instance.vodClass,
  'vodPic': instance.vodPic,
  'vodPicThumb': instance.vodPicThumb,
  'vodPicSlide': instance.vodPicSlide,
  'vodPicScreenshot': instance.vodPicScreenshot,
  'vodBlurb': instance.vodBlurb,
  'vodContent': instance.vodContent,
  'vodRemarks': instance.vodRemarks,
  'vodPubdate': instance.vodPubdate,
  'vodTotal': instance.vodTotal,
  'vodSerial': instance.vodSerial,
  'vodDuration': instance.vodDuration,
  'vodScore': instance.vodScore,
  'vodScoreAll': instance.vodScoreAll,
  'vodScoreNum': instance.vodScoreNum,
  'vodDoubanId': instance.vodDoubanId,
  'vodDoubanScore': instance.vodDoubanScore,
  'vodHits': instance.vodHits,
  'vodHitsDay': instance.vodHitsDay,
  'vodHitsWeek': instance.vodHitsWeek,
  'vodHitsMonth': instance.vodHitsMonth,
  'vodUp': instance.vodUp,
  'vodDown': instance.vodDown,
  'vodStatus': instance.vodStatus,
  'vodIsend': instance.vodIsend,
  'vodLock': instance.vodLock,
  'vodLevel': instance.vodLevel,
  'vodCopyright': instance.vodCopyright,
  'vodPoints': instance.vodPoints,
  'vodPointsPlay': instance.vodPointsPlay,
  'vodPointsDown': instance.vodPointsDown,
  'vodTrysee': instance.vodTrysee,
  'vodPlot': instance.vodPlot,
  'vodPlotName': instance.vodPlotName,
  'vodPlotDetail': instance.vodPlotDetail,
  'vodPlayFrom': instance.vodPlayFrom,
  'vodPlayServer': instance.vodPlayServer,
  'vodPlayNote': instance.vodPlayNote,
  'vodPlayUrl': instance.vodPlayUrl,
  'vodDownFrom': instance.vodDownFrom,
  'vodDownServer': instance.vodDownServer,
  'vodDownNote': instance.vodDownNote,
  'vodDownUrl': instance.vodDownUrl,
  'vodJumpurl': instance.vodJumpurl,
  'vodPwd': instance.vodPwd,
  'vodPwdUrl': instance.vodPwdUrl,
  'vodPwdPlay': instance.vodPwdPlay,
  'vodPwdPlayUrl': instance.vodPwdPlayUrl,
  'vodPwdDown': instance.vodPwdDown,
  'vodPwdDownUrl': instance.vodPwdDownUrl,
  'vodRelVod': instance.vodRelVod,
  'vodRelArt': instance.vodRelArt,
  'vodTag': instance.vodTag,
  'vodLetter': instance.vodLetter,
  'vodColor': instance.vodColor,
  'vodAuthor': instance.vodAuthor,
  'vodBehind': instance.vodBehind,
  'vodState': instance.vodState,
  'vodVersion': instance.vodVersion,
  'vodWeekday': instance.vodWeekday,
  'vodTv': instance.vodTv,
  'vodTpl': instance.vodTpl,
  'vodTplPlay': instance.vodTplPlay,
  'vodTplDown': instance.vodTplDown,
  'vodReurl': instance.vodReurl,
  'vodTime': instance.vodTime,
  'vodTimeAdd': instance.vodTimeAdd,
  'vodTimeHits': instance.vodTimeHits,
  'vodTimeMake': instance.vodTimeMake,
  'vodUrlWithPlayer': instance.vodUrlWithPlayer,
};

_VodPlayer _$VodPlayerFromJson(Map<String, dynamic> json) => _VodPlayer(
  code: json['code'] as String,
  name: json['name'] as String,
  url: json['url'] as String,
  headers: json['headers'] as String,
  parseApi: json['parseApi'] as String,
  extraParseApi: json['extraParseApi'] as String,
  parseSecret: json['parseSecret'] as bool,
  linkFeatures: json['linkFeatures'] as String,
  unLinkFeatures: json['unLinkFeatures'] as String,
  coreParams: (json['coreParams'] as List<dynamic>)
      .map((e) => e as String)
      .toList(),
);

Map<String, dynamic> _$VodPlayerToJson(_VodPlayer instance) =>
    <String, dynamic>{
      'code': instance.code,
      'name': instance.name,
      'url': instance.url,
      'headers': instance.headers,
      'parseApi': instance.parseApi,
      'extraParseApi': instance.extraParseApi,
      'parseSecret': instance.parseSecret,
      'linkFeatures': instance.linkFeatures,
      'unLinkFeatures': instance.unLinkFeatures,
      'coreParams': instance.coreParams,
    };
