// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CryptoService {
  final String buildTime;
  final String pkId;

  const CryptoService({required this.buildTime, required this.pkId});

  static Future<void> responseMagic() =>
      RustLib.instance.api.crateCryptoCryptoServiceResponseMagic();

  @override
  int get hashCode => buildTime.hashCode ^ pkId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CryptoService &&
          runtimeType == other.runtimeType &&
          buildTime == other.buildTime &&
          pkId == other.pkId;
}
