// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bears_api.dart';
import 'api/simple.dart';
import 'crypto.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/recommend_video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 690607456;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_bears_video',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Value> crateApiBearsApiApiServiceFetchDanmakuList({
    required ApiService that,
    required String groupKey,
  });

  Future<Value> crateApiBearsApiApiServiceFetchDanmakuListByIds({
    required ApiService that,
    required PlatformInt64 vodId,
    required PlatformInt64 groupId,
  });

  Future<HomeRecommendData> crateApiBearsApiApiServiceFetchHomeRecommend({
    required ApiService that,
  });

  Future<Value> crateApiBearsApiApiServiceFetchVideoDetail({
    required ApiService that,
    required int videoId,
  });

  Future<Value> crateApiBearsApiApiServiceFetchVideoList({
    required ApiService that,
    required int tid,
    required int page,
  });

  Future<ApiService> crateApiBearsApiApiServiceNew();

  Future<String?> crateApiBearsApiApiServiceResolveEpisodeUrl({
    required ApiService that,
    required String parseApi,
    required String code,
  });

  Future<Value> crateApiBearsApiApiServiceSearch({
    required ApiService that,
    required String keyword,
    required int page,
  });

  Future<void> crateCryptoCryptoServiceResponseMagic();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiService;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ApiServicePtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Value;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Value;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Value> crateApiBearsApiApiServiceFetchDanmakuList({
    required ApiService that,
    required String groupKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_String(groupKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBearsApiApiServiceFetchDanmakuListConstMeta,
        argValues: [that, groupKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceFetchDanmakuListConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_fetch_danmaku_list",
        argNames: ["that", "groupKey"],
      );

  @override
  Future<Value> crateApiBearsApiApiServiceFetchDanmakuListByIds({
    required ApiService that,
    required PlatformInt64 vodId,
    required PlatformInt64 groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_i_64(vodId, serializer);
          sse_encode_i_64(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBearsApiApiServiceFetchDanmakuListByIdsConstMeta,
        argValues: [that, vodId, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceFetchDanmakuListByIdsConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_fetch_danmaku_list_by_ids",
        argNames: ["that", "vodId", "groupId"],
      );

  @override
  Future<HomeRecommendData> crateApiBearsApiApiServiceFetchHomeRecommend({
    required ApiService that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_home_recommend_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBearsApiApiServiceFetchHomeRecommendConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceFetchHomeRecommendConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_fetch_home_recommend",
        argNames: ["that"],
      );

  @override
  Future<Value> crateApiBearsApiApiServiceFetchVideoDetail({
    required ApiService that,
    required int videoId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_i_32(videoId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBearsApiApiServiceFetchVideoDetailConstMeta,
        argValues: [that, videoId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceFetchVideoDetailConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_fetch_video_detail",
        argNames: ["that", "videoId"],
      );

  @override
  Future<Value> crateApiBearsApiApiServiceFetchVideoList({
    required ApiService that,
    required int tid,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_i_32(tid, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBearsApiApiServiceFetchVideoListConstMeta,
        argValues: [that, tid, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceFetchVideoListConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_fetch_video_list",
        argNames: ["that", "tid", "page"],
      );

  @override
  Future<ApiService> crateApiBearsApiApiServiceNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBearsApiApiServiceNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceNewConstMeta =>
      const TaskConstMeta(debugName: "ApiService_new", argNames: []);

  @override
  Future<String?> crateApiBearsApiApiServiceResolveEpisodeUrl({
    required ApiService that,
    required String parseApi,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_String(parseApi, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBearsApiApiServiceResolveEpisodeUrlConstMeta,
        argValues: [that, parseApi, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceResolveEpisodeUrlConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_resolve_episode_url",
        argNames: ["that", "parseApi", "code"],
      );

  @override
  Future<Value> crateApiBearsApiApiServiceSearch({
    required ApiService that,
    required String keyword,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
            that,
            serializer,
          );
          sse_encode_String(keyword, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBearsApiApiServiceSearchConstMeta,
        argValues: [that, keyword, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBearsApiApiServiceSearchConstMeta =>
      const TaskConstMeta(
        debugName: "ApiService_search",
        argNames: ["that", "keyword", "page"],
      );

  @override
  Future<void> crateCryptoCryptoServiceResponseMagic() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateCryptoCryptoServiceResponseMagicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateCryptoCryptoServiceResponseMagicConstMeta =>
      const TaskConstMeta(
        debugName: "crypto_service_response_magic",
        argNames: [],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Value => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Value => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ApiService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Value
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Value
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ValueImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BannerItem dco_decode_banner_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BannerItem(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      reqType: dco_decode_i_32(arr[3]),
      reqContent: dco_decode_String(arr[4]),
      realPackageId: dco_decode_String(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CryptoService dco_decode_crypto_service(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CryptoService(
      buildTime: dco_decode_String(arr[0]),
      pkId: dco_decode_String(arr[1]),
    );
  }

  @protected
  HomeRecommendData dco_decode_home_recommend_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HomeRecommendData(
      banners: dco_decode_list_banner_item(arr[0]),
      videos: dco_decode_list_home_video_section(arr[1]),
    );
  }

  @protected
  HomeVideoSection dco_decode_home_video_section(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return HomeVideoSection(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      typeId: dco_decode_i_32(arr[2]),
      hasMore: dco_decode_bool(arr[3]),
      moreReqType: dco_decode_i_32(arr[4]),
      moreText: dco_decode_String(arr[5]),
      vlist: dco_decode_list_vod_item(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<BannerItem> dco_decode_list_banner_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_banner_item).toList();
  }

  @protected
  List<HomeVideoSection> dco_decode_list_home_video_section(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_home_video_section).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VodItem> dco_decode_list_vod_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vod_item).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VodItem dco_decode_vod_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return VodItem(
      vodId: dco_decode_i_32(arr[0]),
      vodName: dco_decode_String(arr[1]),
      vodPic: dco_decode_String(arr[2]),
      vodRemarks: dco_decode_String(arr[3]),
      typeId: dco_decode_i_32(arr[4]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ApiService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Value
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Value
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ValueImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BannerItem sse_decode_banner_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_reqType = sse_decode_i_32(deserializer);
    var var_reqContent = sse_decode_String(deserializer);
    var var_realPackageId = sse_decode_String(deserializer);
    return BannerItem(
      id: var_id,
      name: var_name,
      content: var_content,
      reqType: var_reqType,
      reqContent: var_reqContent,
      realPackageId: var_realPackageId,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CryptoService sse_decode_crypto_service(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_buildTime = sse_decode_String(deserializer);
    var var_pkId = sse_decode_String(deserializer);
    return CryptoService(buildTime: var_buildTime, pkId: var_pkId);
  }

  @protected
  HomeRecommendData sse_decode_home_recommend_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_banners = sse_decode_list_banner_item(deserializer);
    var var_videos = sse_decode_list_home_video_section(deserializer);
    return HomeRecommendData(banners: var_banners, videos: var_videos);
  }

  @protected
  HomeVideoSection sse_decode_home_video_section(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_typeId = sse_decode_i_32(deserializer);
    var var_hasMore = sse_decode_bool(deserializer);
    var var_moreReqType = sse_decode_i_32(deserializer);
    var var_moreText = sse_decode_String(deserializer);
    var var_vlist = sse_decode_list_vod_item(deserializer);
    return HomeVideoSection(
      id: var_id,
      name: var_name,
      typeId: var_typeId,
      hasMore: var_hasMore,
      moreReqType: var_moreReqType,
      moreText: var_moreText,
      vlist: var_vlist,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<BannerItem> sse_decode_list_banner_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BannerItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_banner_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<HomeVideoSection> sse_decode_list_home_video_section(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HomeVideoSection>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_home_video_section(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VodItem> sse_decode_list_vod_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VodItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vod_item(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VodItem sse_decode_vod_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_vodId = sse_decode_i_32(deserializer);
    var var_vodName = sse_decode_String(deserializer);
    var var_vodPic = sse_decode_String(deserializer);
    var var_vodRemarks = sse_decode_String(deserializer);
    var var_typeId = sse_decode_i_32(deserializer);
    return VodItem(
      vodId: var_vodId,
      vodName: var_vodName,
      vodPic: var_vodPic,
      vodRemarks: var_vodRemarks,
      typeId: var_typeId,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    ApiService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ValueImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    ApiService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiServiceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiService(
    ApiService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ValueImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_banner_item(BannerItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_32(self.reqType, serializer);
    sse_encode_String(self.reqContent, serializer);
    sse_encode_String(self.realPackageId, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_crypto_service(CryptoService self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.buildTime, serializer);
    sse_encode_String(self.pkId, serializer);
  }

  @protected
  void sse_encode_home_recommend_data(
    HomeRecommendData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_banner_item(self.banners, serializer);
    sse_encode_list_home_video_section(self.videos, serializer);
  }

  @protected
  void sse_encode_home_video_section(
    HomeVideoSection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_i_32(self.typeId, serializer);
    sse_encode_bool(self.hasMore, serializer);
    sse_encode_i_32(self.moreReqType, serializer);
    sse_encode_String(self.moreText, serializer);
    sse_encode_list_vod_item(self.vlist, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_banner_item(
    List<BannerItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_banner_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_home_video_section(
    List<HomeVideoSection> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_home_video_section(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_vod_item(List<VodItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vod_item(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vod_item(VodItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.vodId, serializer);
    sse_encode_String(self.vodName, serializer);
    sse_encode_String(self.vodPic, serializer);
    sse_encode_String(self.vodRemarks, serializer);
    sse_encode_i_32(self.typeId, serializer);
  }
}

@sealed
class ApiServiceImpl extends RustOpaque implements ApiService {
  // Not to be used by end users
  ApiServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ApiService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiService,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiServicePtr,
  );

  Future<Value> fetchDanmakuList({required String groupKey}) =>
      RustLib.instance.api.crateApiBearsApiApiServiceFetchDanmakuList(
        that: this,
        groupKey: groupKey,
      );

  Future<Value> fetchDanmakuListByIds({
    required PlatformInt64 vodId,
    required PlatformInt64 groupId,
  }) => RustLib.instance.api.crateApiBearsApiApiServiceFetchDanmakuListByIds(
    that: this,
    vodId: vodId,
    groupId: groupId,
  );

  Future<HomeRecommendData> fetchHomeRecommend() => RustLib.instance.api
      .crateApiBearsApiApiServiceFetchHomeRecommend(that: this);

  Future<Value> fetchVideoDetail({required int videoId}) => RustLib.instance.api
      .crateApiBearsApiApiServiceFetchVideoDetail(that: this, videoId: videoId);

  Future<Value> fetchVideoList({required int tid, required int page}) =>
      RustLib.instance.api.crateApiBearsApiApiServiceFetchVideoList(
        that: this,
        tid: tid,
        page: page,
      );

  Future<String?> resolveEpisodeUrl({
    required String parseApi,
    required String code,
  }) => RustLib.instance.api.crateApiBearsApiApiServiceResolveEpisodeUrl(
    that: this,
    parseApi: parseApi,
    code: code,
  );

  Future<Value> search({required String keyword, required int page}) =>
      RustLib.instance.api.crateApiBearsApiApiServiceSearch(
        that: this,
        keyword: keyword,
        page: page,
      );
}

@sealed
class ValueImpl extends RustOpaque implements Value {
  // Not to be used by end users
  ValueImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ValueImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Value,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Value,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ValuePtr,
  );
}
