[package]
name = "rust_lib_bears_video"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aes = "0.8"
cbc = "0.1"
rand = "0.10.1"
tokio = { version = "1.52.3", features = ["io-util", "sync", "net"] }
reqwest = {version = "0.13.4",features = ["json", "gzip", "brotli", "charset"]}
base64 = "0.22.1"
md5 = "0.8.0"
regex = "1.12.4"
anyhow = "1.0.103"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
