// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/recommend_video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_url`, `make_group_key`, `request`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiService>>
abstract class ApiService implements RustOpaqueInterface {
  Future<Value> fetchDanmakuList({required String groupKey});

  Future<Value> fetchDanmakuListByIds({
    required PlatformInt64 vodId,
    required PlatformInt64 groupId,
  });

  Future<HomeRecommendData> fetchHomeRecommend();

  Future<Value> fetchVideoDetail({required int videoId});

  Future<Value> fetchVideoList({required int tid, required int page});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ApiService> newInstance() =>
      RustLib.instance.api.crateApiBearsApiApiServiceNew();

  Future<String?> resolveEpisodeUrl({
    required String parseApi,
    required String code,
  });

  Future<Value> search({required String keyword, required int page});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Value>>
abstract class Value implements RustOpaqueInterface {}
