// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_schema`, `database_path`, `episode_download_from_row`, `episode_download_select`, `episode_history_from_row`, `episode_history_select`, `favorite_from_row`, `now_ms`, `open_connection`, `query_downloads`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<void> initializeDatabase({required String directory}) => RustLib
    .instance
    .api
    .crateApiDatabaseInitializeDatabase(directory: directory);

Future<List<String>> searchHistoryGetRecent({required int limit}) =>
    RustLib.instance.api.crateApiDatabaseSearchHistoryGetRecent(limit: limit);

Future<void> searchHistorySave({required String keyword}) =>
    RustLib.instance.api.crateApiDatabaseSearchHistorySave(keyword: keyword);

Future<void> searchHistoryClear() =>
    RustLib.instance.api.crateApiDatabaseSearchHistoryClear();

Future<bool> favoriteIsSaved({required PlatformInt64 videoId}) =>
    RustLib.instance.api.crateApiDatabaseFavoriteIsSaved(videoId: videoId);

Future<void> favoriteSave({
  required PlatformInt64 videoId,
  required String videoTitle,
  required String videoPoster,
  required String videoDetailJson,
}) => RustLib.instance.api.crateApiDatabaseFavoriteSave(
  videoId: videoId,
  videoTitle: videoTitle,
  videoPoster: videoPoster,
  videoDetailJson: videoDetailJson,
);

Future<void> favoriteRemove({required PlatformInt64 videoId}) =>
    RustLib.instance.api.crateApiDatabaseFavoriteRemove(videoId: videoId);

Future<String?> favoriteGetDetailJson({required PlatformInt64 videoId}) =>
    RustLib.instance.api.crateApiDatabaseFavoriteGetDetailJson(
      videoId: videoId,
    );

Future<List<FavoriteRecord>> favoriteGetAll() =>
    RustLib.instance.api.crateApiDatabaseFavoriteGetAll();

Future<EpisodeHistoryRecord?> episodeHistoryGet({
  required PlatformInt64 videoId,
}) => RustLib.instance.api.crateApiDatabaseEpisodeHistoryGet(videoId: videoId);

Future<List<EpisodeHistoryRecord>> episodeHistoryGetAll() =>
    RustLib.instance.api.crateApiDatabaseEpisodeHistoryGetAll();

Future<void> episodeHistorySaveSelection({
  required PlatformInt64 videoId,
  required int sourceIndex,
  required int episodeIndex,
}) => RustLib.instance.api.crateApiDatabaseEpisodeHistorySaveSelection(
  videoId: videoId,
  sourceIndex: sourceIndex,
  episodeIndex: episodeIndex,
);

Future<void> episodeHistorySaveProgress({
  required PlatformInt64 videoId,
  required int sourceIndex,
  required int episodeIndex,
  required PlatformInt64 watchedPositionMs,
  required PlatformInt64 totalDurationMs,
}) => RustLib.instance.api.crateApiDatabaseEpisodeHistorySaveProgress(
  videoId: videoId,
  sourceIndex: sourceIndex,
  episodeIndex: episodeIndex,
  watchedPositionMs: watchedPositionMs,
  totalDurationMs: totalDurationMs,
);

Future<void> episodeHistorySaveMetadata({
  required PlatformInt64 videoId,
  required int sourceIndex,
  required int episodeIndex,
  required String videoTitle,
  required String videoPoster,
  required String videoDetailJson,
  required String sourceName,
  required String episodeLabel,
}) => RustLib.instance.api.crateApiDatabaseEpisodeHistorySaveMetadata(
  videoId: videoId,
  sourceIndex: sourceIndex,
  episodeIndex: episodeIndex,
  videoTitle: videoTitle,
  videoPoster: videoPoster,
  videoDetailJson: videoDetailJson,
  sourceName: sourceName,
  episodeLabel: episodeLabel,
);

Future<void> episodeHistoryClear() =>
    RustLib.instance.api.crateApiDatabaseEpisodeHistoryClear();

Future<EpisodeDownloadRecord?> episodeDownloadGet({
  required PlatformInt64 videoId,
  required String sourceName,
  required int episodeIndex,
}) => RustLib.instance.api.crateApiDatabaseEpisodeDownloadGet(
  videoId: videoId,
  sourceName: sourceName,
  episodeIndex: episodeIndex,
);

Future<void> episodeDownloadSave({required EpisodeDownloadRecord record}) =>
    RustLib.instance.api.crateApiDatabaseEpisodeDownloadSave(record: record);

Future<void> episodeDownloadDelete({
  required PlatformInt64 videoId,
  required String sourceName,
  required int episodeIndex,
}) => RustLib.instance.api.crateApiDatabaseEpisodeDownloadDelete(
  videoId: videoId,
  sourceName: sourceName,
  episodeIndex: episodeIndex,
);

Future<List<EpisodeDownloadRecord>> episodeDownloadGetForVideo({
  required PlatformInt64 videoId,
}) => RustLib.instance.api.crateApiDatabaseEpisodeDownloadGetForVideo(
  videoId: videoId,
);

Future<List<EpisodeDownloadRecord>> episodeDownloadGetAll() =>
    RustLib.instance.api.crateApiDatabaseEpisodeDownloadGetAll();

class EpisodeDownloadRecord {
  final PlatformInt64 videoId;
  final String videoTitle;
  final String videoPoster;
  final String videoDetailJson;
  final String sourceName;
  final int episodeIndex;
  final String episodeLabel;
  final String remoteUrl;
  final String localPath;
  final String headersJson;
  final PlatformInt64 downloadedAt;
  final PlatformInt64 fileSizeBytes;

  const EpisodeDownloadRecord({
    required this.videoId,
    required this.videoTitle,
    required this.videoPoster,
    required this.videoDetailJson,
    required this.sourceName,
    required this.episodeIndex,
    required this.episodeLabel,
    required this.remoteUrl,
    required this.localPath,
    required this.headersJson,
    required this.downloadedAt,
    required this.fileSizeBytes,
  });

  @override
  int get hashCode =>
      videoId.hashCode ^
      videoTitle.hashCode ^
      videoPoster.hashCode ^
      videoDetailJson.hashCode ^
      sourceName.hashCode ^
      episodeIndex.hashCode ^
      episodeLabel.hashCode ^
      remoteUrl.hashCode ^
      localPath.hashCode ^
      headersJson.hashCode ^
      downloadedAt.hashCode ^
      fileSizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpisodeDownloadRecord &&
          runtimeType == other.runtimeType &&
          videoId == other.videoId &&
          videoTitle == other.videoTitle &&
          videoPoster == other.videoPoster &&
          videoDetailJson == other.videoDetailJson &&
          sourceName == other.sourceName &&
          episodeIndex == other.episodeIndex &&
          episodeLabel == other.episodeLabel &&
          remoteUrl == other.remoteUrl &&
          localPath == other.localPath &&
          headersJson == other.headersJson &&
          downloadedAt == other.downloadedAt &&
          fileSizeBytes == other.fileSizeBytes;
}

class EpisodeHistoryRecord {
  final PlatformInt64 videoId;
  final int sourceIndex;
  final int episodeIndex;
  final PlatformInt64 watchedPositionMs;
  final PlatformInt64 totalDurationMs;
  final String videoTitle;
  final String videoPoster;
  final String videoDetailJson;
  final String sourceName;
  final String episodeLabel;
  final PlatformInt64 updatedAt;

  const EpisodeHistoryRecord({
    required this.videoId,
    required this.sourceIndex,
    required this.episodeIndex,
    required this.watchedPositionMs,
    required this.totalDurationMs,
    required this.videoTitle,
    required this.videoPoster,
    required this.videoDetailJson,
    required this.sourceName,
    required this.episodeLabel,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      videoId.hashCode ^
      sourceIndex.hashCode ^
      episodeIndex.hashCode ^
      watchedPositionMs.hashCode ^
      totalDurationMs.hashCode ^
      videoTitle.hashCode ^
      videoPoster.hashCode ^
      videoDetailJson.hashCode ^
      sourceName.hashCode ^
      episodeLabel.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpisodeHistoryRecord &&
          runtimeType == other.runtimeType &&
          videoId == other.videoId &&
          sourceIndex == other.sourceIndex &&
          episodeIndex == other.episodeIndex &&
          watchedPositionMs == other.watchedPositionMs &&
          totalDurationMs == other.totalDurationMs &&
          videoTitle == other.videoTitle &&
          videoPoster == other.videoPoster &&
          videoDetailJson == other.videoDetailJson &&
          sourceName == other.sourceName &&
          episodeLabel == other.episodeLabel &&
          updatedAt == other.updatedAt;
}

class FavoriteRecord {
  final PlatformInt64 videoId;
  final String videoTitle;
  final String videoPoster;
  final String videoDetailJson;
  final PlatformInt64 createdAt;

  const FavoriteRecord({
    required this.videoId,
    required this.videoTitle,
    required this.videoPoster,
    required this.videoDetailJson,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      videoId.hashCode ^
      videoTitle.hashCode ^
      videoPoster.hashCode ^
      videoDetailJson.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FavoriteRecord &&
          runtimeType == other.runtimeType &&
          videoId == other.videoId &&
          videoTitle == other.videoTitle &&
          videoPoster == other.videoPoster &&
          videoDetailJson == other.videoDetailJson &&
          createdAt == other.createdAt;
}
