// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<ParseVideoResult> parseVideoUrl({required String jsonText}) =>
    RustLib.instance.api.crateApiVideoParseApiParseVideoUrl(jsonText: jsonText);

class ParseVideoResult {
  final String url;
  final String mediaType;

  const ParseVideoResult({required this.url, required this.mediaType});

  @override
  int get hashCode => url.hashCode ^ mediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseVideoResult &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          mediaType == other.mediaType;
}
